name: Symlink Validator

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  validate_symlinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Symlinks
        id: symlink_check
        run: |
          BROKEN_LINKS=$(mktemp)
    
          find . -type l -print0 | while IFS= read -r -d $'\0' symlink; do
              # Check if the target of the symlink exists
              if ! test -e "$symlink"; then
                  # Add path to the temporary file
                  echo "$symlink" >> "$BROKEN_LINKS"
                  echo "::error file=$symlink::Broken symlink found: $symlink points to a non-existent target."
              fi
          done
          
          if [ -s "$BROKEN_LINKS" ]; then
              echo "FATAL: Broken symlinks detected."
              rm "$BROKEN_LINKS"
              exit 1 
          else
              echo "All symlinks are valid. The repository is clean."
              rm "$BROKEN_LINKS"
          fi
